spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dolar-api
    username: postgres
    password: root

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none # Hibernate não irá modificar o banco de dados
        format_sql: false
      jdbc:
        lob:
          non_contextual_creation: true # Para evitar problemas de versões do postgres
